stages:
  - test
  - deploy_demo

test_task:
  stage: test
  script:
    - make test
  only:
    - master
  cache:
    paths:
      - venv/

deploy_demo_task:
  stage: deploy_demo
  script:
    - fab setenv:demo update
  only:
    - master
